image: docker.redoo.cloud/gitlab-ci:php7.3

variables:
  SONAR_URL: "https://sonarcube.redoo.network:9001"
  SOURCE_PATH: "."
  PROJECT_KEY: "FlexAPIClientJS"
  
stages:
  - sonarqube
  - packaging

sonarqube_master_job:
  stage: sonarqube
  only:
    - master
  script:
    - sonar-scanner -X -Dsonar.projectBaseDir=. -Dsonar.login=$SONAR_TOKEN
    
deploy:
  stage: packaging
  only:
    - /^v.*$/
  except: 
    - branches
  script:
    - npm publish
