variables:
  SONAR_URL: "https://sonarcube.redoo.network:9001"
  SONAR_LOGIN: "fca2c553f26f2a8d5ea5479df82ad9155890051f"
  SOURCE_PATH: "."
  PROJECT_KEY: "FlexAPIClientJS"
  
stages:
  - test

sonarqube_master_job:
  stage: test
  only:
    - master
  image: newtmitch/sonar-scanner
  when: manual    
  script:
    - sonar-scanner -X -Dsonar.host.url=$SONAR_URL -Dsonar.projectKey=$PROJECT_KEY -Dsonar.login=$SONAR_LOGIN -Dsonar.sources=$SOURCE_PATH