image: docker.redoo-networks.com/redoo-networks/docker-ci-base

variables:
  SOURCE_PATH: "."
  PROJECT_KEY: "FlexAPIClientJS"
  
stages:
  - sonarqube
  - packaging

sonarqube_master_job:
  stage: sonarqube
  only:
    - master
  script:
    - sonar-scanner -X -Dsonar.projectBaseDir=. -Dsonar.login=$SONAR_TOKEN -Dsonar.host.url=$SONAR_HOST
    
deploy:
  stage: packaging
  only:
    - /^v.*$/
  except: 
    - branches
  script:
    - npm config set //registry.npmjs.org/:_authToken $NPM_TOKEN
    - npm publish --access=public
