variables:
  SONAR_URL: "https://sonarcube.redoo.network:9001"
  SONAR_LOGIN: "fca2c553f26f2a8d5ea5479df82ad9155890051f"
  SOURCE_PATH: "."
  PROJECT_KEY: "FlexAPIClientJS"
  
stages:
  - sonarqube

sonarqube_master_job:
  stage: sonarqube
  only:
    - sonarqube
  image: docker.redoo.cloud:5043/gitlab-ci:php7.3
  when: manual    
  script:
    - sonar-scanner -X -Dsonar.projectBaseDir=.